version: "3.7"

services:
  postgresql:
    image: postgres:latest
    container_name: polyfit-postgresql
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  # migrate:
  #   image: migrate/migrate
  #   container_name: polyfit-migrations
  #   networks:
  #     - default
  #   volumes:
  #     - ./migrations:/migrations
  #   command:
  #     [
  #       "-path",
  #       "./migrations",
  #       "-database",
  #       "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgresql/${DB_DATABASE}?sslmode=disable",
  #       "up",
  #     ]
  #   depends_on:
  #     - postgresql

  server:
    container_name: polyfit-app
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    # command: ./wait-for-postgres.sh ./${APP_NAME}
    networks:
      - default
    depends_on:
      - postgresql
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./logs/all.log:/opt/polyfit/logs/all.log
    env_file:
      - .env
